### ISSUE TITLE
ng serve

### ISSUE THREAD

**Issue by VZhyrytskiy** [sergous/angular5-course#10]
При запске проекта Task4 возникает ошибка

ERROR in src/app/components/products/product-list/product-list.component.ts(17,5): error TS2322: Type 'Promise<Product[]>' is not assignable to type 'Product[]'.
  Property 'includes' is missing in type 'Promise<Product[]>'.
В поле products: Product[]; присваивается промис.

**Comment by sergous** [comment]
https://github.com/sergous/angular5-course/commit/5745c5d994f29db27e6f9bbb6754876d8a85cb5e
