### ISSUE TITLE
products.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [sergous/angular5-course#11]
async getProducts() {
    return Promise.resolve([
      new Product("Book", "Bestseller of this summers", 20, ProductCategory.equivalents, true),
      new Product("Apple", "Green but sweet", 1, ProductCategory.ingredients, true),
    ]);
  }
Тут нет необходимости выполнять Promise.resolve(), так как результат асинхронного метода всеравно будет промис, независимо от того, что вы вернете. Поэтому можно просто return [...]

**Comment by sergous** [comment]
https://github.com/sergous/angular5-course/commit/b673d586def1c5ba314f88c538f7fa2ed7cda034
