### ISSUE TITLE
addProduct + removeProduct (cart.service.ts)

### ISSUE THREAD

**Issue by VZhyrytskiy** [sergous/angular5-course#3]
В методе addProduct происходит мутирование данных, а в методе removeProduct создается новый массив. Может быть стоит использовать один подход, например, всегда создавать новый массив или всегда мутировать. Тогда переход из одного подхода к другому, если такой понадобиться в будущем, будет проще реализовать.

**Comment by sergous** [comment]
Понял, тогда я буду создавать, чтобы можно было легко перейти на стейты.
