### ISSUE TITLE
config-options.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [sergous/angular5-course#8]
Такое внедрение сервиса выбрано в качестве эксперимента? 
  constructor(
    @Inject(forwardRef(() => LocalStorageService)) public localStorageService: LocalStorageService
  ) { }

**Comment by sergous** [comment]
I did not remember the reason, seem works without forwardRef.
https://github.com/sergous/angular5-course/commit/6285ea48e1bfdfbbd3e3145c9a5b2dbe05653ac9
