### ISSUE TITLE
constants.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [sergous/angular5-course#9]
Для этого сервиса ConstantsService не требовалось создавать класс. 
export class ConstantsService {
  constructor(
    public title: string,
    public version: string,
  ) { }
Если вы создали класс и добавили декоратор @Injectable(), то старайтесь в конструкторе не использовать НЕ зависимости. Сейчас это работает, но может не работать в будущем. Так как Ангуляр будет искать title и version как сервисы.

**Comment by sergous** [comment]
I did not know how to create config constants, got it in routing http lessons (https://github.com/sergous/An2-5-HttpClient/blob/angular-cource-5-http-client/src/app/users/users.config.ts).

**Comment by sergous** [comment]
https://github.com/sergous/angular5-course/commit/3daf4f48afe750eee40046211ccb8961be7d3d81
